version: '3'

services:
  reverse-proxy:
    image: traefik:maroilles-alpine
    command: --api --docker
    ports:
      - 8000:80
      - 8001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.basic.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.basic.protocol=http"
      - "traefik.basic.port=80"